@baseUrl = http://localhost:3333

# @name create_a_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name":"Test Client",
    "email":"test@example.com",
    "password": "123123"
}