version: '3.8'

services:
  postgres:
    container_name: nest-clean-pg
    image: postgres
    ports:
      - 9988:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-clean
      PGDATA: /data/postgres # pasta de dados do postgres
    volumes:
        - ./data/pg:/data/postgres # linkando pasta de dados postgres com pasta interna no vscode